security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CA:          ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_CA, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:   ^/(_(profiler|wdt|error)|css|images|js)/
            security:  false

        api_login:
            pattern:   ^/api/login
            stateless: true
            logout:    false
            anonymous: true
            form_login:
                login_path:         fos_user_security_login
                check_path:         api_security_check
                username_parameter: username
                password_parameter: password
                success_handler:    lexik_jwt_authentication.handler.authentication_success
                failure_handler:    lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            logout:    false
            anonymous: false
            lexik_jwt: ~

        front:
            pattern:   ^/
            anonymous: true
            logout:
                path:  fos_user_security_logout
            form_login:
                csrf_provider:       security.csrf.token_manager
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check
                default_target_path: dashboard
                username_parameter:  username
                password_parameter:  password
                success_handler:     front.authentication.success_handler
                failure_handler:     ~
                require_previous_session: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
